---
id: "vie-dev"
desc: "vie, under developement"

logging:
  path: "local/log/"

data:
  path: "data/papers"
  bib-path: "data/references"
mongo:
  connection-string: "XXXXXXXXXXX"
  database: "XXXXXXX"